services:
  traefik:
    image: traefik:3.6
    restart: unless-stopped
    ports:
      - "80:80"
    command:
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --entryPoints.web.address=:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_public
    networks:
      - default
      - traefik_public

  app-nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    restart: unless-stopped
    volumes:
      - .:/app
      - storage:/app/storage/app
    environment:
      DOMAIN: ${APP_DOMAIN}
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_public
      - traefik.http.routers.appNginx.rule=Host(`${APP_DOMAIN}`)
      - traefik.http.routers.appNginx.entryPoints=web
      - traefik.http.services.appNginx.loadBalancer.server.port=80
    networks:
      - default
      - traefik_public

  app-php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
      args:
        INSTALL_XDEBUG: "true"
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
       - .env
    volumes:
      - .:/app
      - storage:/app/storage/app
    depends_on:
      - db
    networks:
      - default

  app-node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - .:/app
    ports:
      - "5173:5173"
    command: sh -c "until [ -f .ready ]; do sleep 1; done && npm run dev"
    depends_on:
      - app-php-fpm
    networks:
      - default

  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - './docker/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
    networks:
      - default

networks:
  traefik_public:
  default:

volumes:
  storage:
  db:
